name: Test Retroblog

on: [push]

jobs:
  Lint-and-Test:
    name: Lint-and-Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Install packages
      run: mkdir bin && cd bin && sudo apt install -y curl unzip build-essential python3
    - name: Download chromdriver
      run: curl --output chromedriver.zip https://chromedriver.storage.googleapis.com/98.0.4758.102/chromedriver_linux64.zip
    - name: Extract chromdriver
      run: unzip chromedriver.zip && rm chromedriver.zip
    - name: Pylint
      # run: pip install -r requirements.txt ; python -m pylint $(find tests -name *.py)
      run: ls -la && pwd
#    - name: PyTest
#      run: pip install -r requirements.txt ; python -m pytest
